### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by ddesmond** [geoffroygivry/CyclopsVFX-Polyphemus#1]
Hi Mr G.
i see regular commits and i was wondering what is the status of the project?
how can i test it?
thanks!

**Comment by geoffroygivry** [comment]
Hi Aleks, 
Many thanks for your email and hope you are well. 
I am actively working on CyclopsVFX to be able to release a first beta version for September at the very earliest. 

The first version of CyclopsVFX will aim at : 

- Having a fully working web app (Polyphemus) working flawlessly with the python framework (Unity) for Maya and Nuke. ClarisseIFX and Houdini will come later.
- Having simple but full featured publishing system.
- Having a Dailies submission system.
- having a basic API.
- Having a documentation.
- having video tutorials for getting started with CyclopsVFX, step by step installation and short videos of using both Polyphemus and Unity.
- Unity will work on Linux (CentOS, Fedora and Ubuntu) and Windows10. OSX will come shortly after this release as it needs further unit testing.

A lot of these tasks are in good shape already, The database system is working with MongoDB and it can be hooked very easily on any mongodb instances. 

I really hope I will be on time for September. I'm moving back to London in 4 weeks time with my wife and our 2 children. I will be super busy with our move but If you have any questions please let me know and I will be more than happy to answer to you ASAP.

Speak to you soon Aleks!
Geoff

**Comment by ddesmond** [comment]
First thanks for fast response!
Ive managed to clone it and run mongo on my vm instance, but was haning on the interface part ^^
Great roadmap! Good luck with the move!
ok, ill follow the repo, and test on centos and win10 np, mention me and ill make a fresh clone.

Great to see someone is implementing Clarisse too, and great work so far!

**Comment by geoffroygivry** [comment]
Hi Aleks, thank you so much for the kind words and the encouragement! That makes me want to work twice harder! :-)
I'll definitely keep you in the loop when I've got a fresh copy ready to be used. I am planning to create for Polyphemus a Docker image that you can use on a server or a local computer. The easier it is to setup, the better!
Again thank you very much for your positive words, it means a lot! 
Geoff

**Comment by ddesmond** [comment]
Hey saw some great updates in commits, how to get in touch for contribution / help?
lmk

**Comment by geoffroygivry** [comment]
Hey Aleks, Please PM me at geoff.givry AT gmail.com and will be able to talk! ;-)
