### ISSUE TITLE
Module pyrabbit2

### ISSUE THREAD

**Issue by lunauser** [geoffroygivry/CyclopsVFX-Polyphemus#10]
Hi!

Try this module https://github.com/deslum/pyrabbit2. This is fork pyrabbit with new features and support

**Comment by geoffroygivry** [comment]
Hey Lunauser, many thanks for the link, we'll definitely check this very soon! :) 
Have a great day!
Geoff

**Comment by ccding** [comment]
It is spam. Opening identical issues in 28 repos to advertise your project is definitely a spam.

**Comment by ddesmond** [comment]
Then, we will close this issue :)
