### ISSUE TITLE
WooHoo...... waiting for the 1st release of CyclopsVFX!! 

### ISSUE THREAD

**Issue by tws0002** [geoffroygivry/CyclopsVFX-Polyphemus#3]
WooHoo...... waiting for the 1st release of CyclopsVFX!! 
keep it up, man. 
Thanks for the hard work

Thanks 
Desmond

**Comment by geoffroygivry** [comment]
Thank you for your kind words my friend! :) Now CyclopsVFX is lucky to have @ddesmond on board with us to help making it even better! 
We still have a lot to do to reach the roadmap before the release but any encouragements like you do is precious to us! :) 
Thanks a lot Desmond!
Geoff
